version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'ruby'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'javascript'
