# Configuraci?n m?nima
title: "Mi Portal Digital"
description: "Portal profesional"
url: "https://dwight-trujillo.github.io"
baseurl: "/mi-portal-digital"

# Plugins desactivados
plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - docs
  - _layouts
  - _includes
  - _posts
